### ISSUE TITLE
Propagate error to error handler

### ISSUE THREAD

**Issue by paglias** [koajs/bodyparser#36]
Hello,

I have a Koa 2 app like this

```
  app
    .use(errorHandler)
    .use(bodyParser)
```

bodyParser:

```
bodyParser({
  formLimit: 0,
  onerror (err, ctx) {
    throw new BadRequest('Error parsing body.', err);
  },
});
```

errorHandler:

```
  try {
    await next();
  } catch (err) {
    // Do something with err
  }
```

when an error is thrown in `onerror` it doesn't get passed to the errorHandler like normal requests but instead throw:

```
error: UnprocessableEntityError: body parse error
    at Object.throw (/Users/matteo/dev/transactions-server/node_modules/koa/lib/context.js:91:23)
    at onerror (bodyParser.js:9:5)
    at /Users/matteo/dev/transactions-server/node_modules/koa-bodyparser/index.js:61:15
    at process._tickCallback (node.js:401:9)
```

there's no way of handling error like normal response handlers?

I can use `ctx.throw` but would really like to propagate the error

**Comment by dead-horse** [comment]
```js
'use strict';

const koa = require('koa');
const bodyParser = require('koa-body-parser');
const convert = require('koa-convert');
const error = require('koa-error');

const app = new koa();
app.use(convert(error()));
app.use(convert(bodyParser({
  onerror(err) {
    err.message = `onerror: ${err.message}`;
    throw err;
  }
})));

app.use(function (ctx) {
  ctx.body = 'hello';
});

app.listen(3000);

```

i tried like this, everything is fine, can you give a simple reproduce code?

**Comment by paglias** [comment]
@dead-horse while I was trying to reproduce the bug I found a typo in my code... :( I'm sorry
