### ISSUE TITLE
Koa Body Parser Unexpected Token

### ISSUE THREAD

**Issue by racerxdl** [koajs/bodyparser#79]
Trying to run koa-bodyparser here I get this error:

```
/home/lucas/Works/backend/node_modules/koa-bodyparser/index.js:72
  return async function bodyParser(ctx, next) {
               ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/lucas/Works/backend/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

My code is:

```jsx
/**
 * Created by Lucas Teske on 11/04/17.
 * @flow
 */

import 'isomorphic-fetch';

import Koa from 'koa';
import cors from 'koa-cors';
import graphqlHTTP from 'koa-graphql';
import convert from 'koa-convert';
import logger from 'koa-logger';
import koaSsl from 'koa-ssl';
import route from 'koa-route';
import bodyParser from 'koa-bodyparser';


const app = new Koa();
app.use(koaSsl({ disabled: !sslEnforce }));
app.use(logger());
app.use(bodyParser());
```

**Comment by Kyoloro** [comment]
+1

**Comment by dead-horse** [comment]
need node 7.6+ or use babel compile node_modules/koa-bodyparser

**Comment by racerxdl** [comment]
I'm using babel. Check my code, is using es2015. Still same error.

**Comment by racerxdl** [comment]
My babelrc btw:

```json
{
  "plugins": [
    "typecheck", "syntax-flow", "transform-flow-strip-types", ["transform-class-properties", { "spec": true }]
  ],
  "sourceMaps": "both",
  "presets": ["es2015", "stage-1"]
}
```
